import React, { useState, useEffect, useRef } from 'react';
// Assuming Tailwind CSS is configured and available globally for styling

// Player Data from the uploaded CSV file, with team and custom tier adjustments.
const mockPlayersData = [
    { id: 1, name: 'JaMarr Chase', position: 'WR', team: 'CIN', adp: 2.05, tier: 'Tier 1' },
    { id: 2, name: 'Bijan Robinson', position: 'RB', team: 'ATL', adp: 2.79, tier: 'Tier 1' },
    { id: 3, name: 'Saquon Barkley', position: 'RB', team: 'PHI', adp: 3.08, tier: 'Tier 1' },
    { id: 4, name: 'Justin Jefferson', position: 'WR', team: 'MIN', adp: 5.24, tier: 'Tier 1' },
    { id: 5, name: 'CeeDee Lamb', position: 'WR', team: 'DAL', adp: 5.3, tier: 'Tier 1' },
    { id: 6, name: 'Christian McCaffrey', position: 'RB', team: 'SF', adp: 13.72, tier: 'Tier 1' }, // Moved up
    { id: 7, name: 'Jahmyr Gibbs', position: 'RB', team: 'DET', adp: 5.18, tier: 'Tier 2' }, // Moved down
    { id: 8, name: 'Derrick Henry', position: 'RB', team: 'BAL', adp: 8.21, tier: 'Tier 2' },
    { id: 9, name: 'Puka Nacua', position: 'WR', team: 'LAR', adp: 11.42, tier: 'Tier 2' },
    { id: 10, name: 'Amon-Ra St. Brown', position: 'WR', team: 'DET', adp: 13.17, tier: 'Tier 2' },
    { id: 11, name: 'Nico Collins', position: 'WR', team: 'HOU', adp: 9.2, tier: 'Tier 2' },
    { id: 12, name: 'Brian Thomas Jr.', position: 'WR', team: 'JAX', adp: 11.07, tier: 'Tier 2' },
    { id: 13, name: 'Ashton Jeanty', position: 'RB', team: 'LV', adp: 13.89, tier: 'Tier 2' },
    { id: 14, name: 'Jonathan Taylor', position: 'RB', team: 'IND', adp: 16.47, tier: 'Tier 3' },
    { id: 15, name: 'A.J. Brown', position: 'WR', team: 'PHI', adp: 16.79, tier: 'Tier 3' },
    { id: 16, name: 'Drake London', position: 'WR', team: 'ATL', adp: 17.23, tier: 'Tier 3' },
    { id: 17, name: 'De\'Von Achane', position: 'RB', team: 'MIA', adp: 17.55, tier: 'Tier 3' },
    { id: 18, name: 'Josh Jacobs', position: 'RB', team: 'GB', adp: 19.16, tier: 'Tier 3' },
    { id: 19, name: 'Malik Nabers', position: 'WR', team: 'NYG', adp: 11.17, tier: 'Tier 3' }, // Moved down
    { id: 20, name: 'Breece Hall', position: 'RB', team: 'NYJ', adp: 42.11, tier: 'Tier 3' }, // Tier moved up
    { id: 21, name: 'Kyren Williams', position: 'RB', team: 'LAR', adp: 24.83, tier: 'Tier 4' },
    { id: 22, name: 'Josh Allen', position: 'QB', team: 'BUF', adp: 26.08, tier: 'Tier 4' },
    { id: 23, name: 'Lamar Jackson', position: 'QB', team: 'BAL', adp: 26.7, tier: 'Tier 4' },
    { id: 24, name: 'Tee Higgins', position: 'WR', team: 'CIN', adp: 28.34, tier: 'Tier 5' }, // Moved down
    { id: 25, name: 'Chase Brown', position: 'RB', team: 'CIN', adp: 28.53, tier: 'Tier 4' },
    { id: 26, name: 'Joe Burrow', position: 'QB', team: 'CIN', adp: 47.47, tier: 'Tier 4' }, // Moved up
    { id: 27, name: 'Brock Bowers', position: 'TE', team: 'LV', adp: 21.57, tier: 'Tier 5' }, // Moved down, per TE notes
    { id: 28, name: 'Trey McBride', position: 'TE', team: 'ARI', adp: 25.13, tier: 'Tier 4' }, // Moved per TE notes
    { id: 29, name: 'Tyreek Hill', position: 'WR', team: 'MIA', adp: 32.48, tier: 'Tier 5' },
    { id: 30, name: 'Mike Evans', position: 'WR', team: 'TB', adp: 28.07, tier: 'Tier 5' },
    { id: 31, name: 'Jaxon Smith-Njigba', position: 'WR', team: 'SEA', adp: 33.59, tier: 'Tier 5' },
    { id: 32, name: 'James Cook', position: 'RB', team: 'BUF', adp: 34.37, tier: 'Tier 5' },
    { id: 33, name: 'Davante Adams', position: 'WR', team: 'NYJ', adp: 35.72, tier: 'Tier 5' },
    { id: 34, name: 'Jalen Hurts', position: 'QB', team: 'PHI', adp: 36.63, tier: 'Tier 5' },
    { id: 35, name: 'Sam LaPorta', position: 'TE', team: 'DET', adp: 60.77, tier: 'Tier 5' }, // Moved up
    { id: 36, name: 'Mark Andrews', position: 'TE', team: 'BAL', adp: 67.7, tier: 'Tier 5' }, // Re-tiered for grouping
    { id: 37, name: 'Travis Kelce', position: 'TE', team: 'KC', adp: 89.96, tier: 'Tier 5' }, // Re-tiered for grouping
    { id: 38, name: 'Jayden Daniels', position: 'QB', team: 'WAS', adp: 33.78, tier: 'Tier 6' }, // Moved down
    { id: 39, name: 'Garrett Wilson', position: 'WR', team: 'NYJ', adp: 39.3, tier: 'Tier 6' },
    { id: 40, name: 'Marvin Harrison Jr.', position: 'WR', team: 'ARI', adp: 40.11, tier: 'Tier 6' },
    { id: 41, name: 'Kenneth Walker III', position: 'RB', team: 'SEA', adp: 40.47, tier: 'Tier 6' },
    { id: 42, name: 'Terry McLaurin', position: 'WR', team: 'WAS', adp: 42.15, tier: 'Tier 6' },
    { id: 43, name: 'George Kittle', position: 'TE', team: 'SF', adp: 21.8, tier: 'Tier 6' },
    { id: 44, name: 'T.J. Hockenson', position: 'TE', team: 'MIN', adp: 76.99, tier: 'Tier 6' },
    { id: 45, name: 'Dallas Goedert', position: 'TE', team: 'PHI', adp: 121.68, tier: 'Tier 6' },
    { id: 46, name: 'DK Metcalf', position: 'WR', team: 'SEA', adp: 45.72, tier: 'Tier 7' },
    { id: 47, name: 'Chuba Hubbard', position: 'RB', team: 'CAR', adp: 46.97, tier: 'Tier 7' },
    { id: 48, name: 'James Conner', position: 'RB', team: 'ARI', adp: 47.98, tier: 'Tier 7' },
    { id: 49, name: 'Alvin Kamara', position: 'RB', team: 'NO', adp: 48.7, tier: 'Tier 7' },
    { id: 50, name: 'DJ Moore', position: 'WR', team: 'CHI', adp: 48.99, tier: 'Tier 7' },
    { id: 51, name: 'Courtland Sutton', position: 'WR', team: 'DEN', adp: 50.1, tier: 'Tier 7' },
    { id: 52, name: 'TreVeyon Henderson', position: 'RB', team: 'NE', adp: 54.08, tier: 'Tier 8' },
    { id: 53, name: 'Xavier Worthy', position: 'WR', team: 'KC', adp: 54.46, tier: 'Tier 8' },
    { id: 54, name: 'Zay Flowers', position: 'WR', team: 'BAL', adp: 56.08, tier: 'Tier 8' },
    { id: 55, name: 'David Montgomery', position: 'RB', team: 'DET', adp: 57.34, tier: 'Tier 9' },
    { id: 56, name: 'DeVonta Smith', position: 'WR', team: 'PHI', adp: 57.64, tier: 'Tier 9' },
    { id: 57, name: 'George Pickens', position: 'WR', team: 'PIT', adp: 58.13, tier: 'Tier 9' },
    { id: 58, name: 'Calvin Ridley', position: 'WR', team: 'TEN', adp: 58.46, tier: 'Tier 9' },
    { id: 59, name: 'Tetairoa McMillan', position: 'WR', team: 'CAR', adp: 60.49, tier: 'Tier 9' },
    { id: 60, name: 'D\'Andre Swift', position: 'RB', team: 'CHI', adp: 60.49, tier: 'Tier 9' },
    { id: 61, name: 'Rachaad White', position: 'RB', team: 'TB', adp: 131.68, tier: 'Tier 9' }, // Moved up
    { id: 62, name: 'Omarion Hampton', position: 'RB', team: 'LAC', adp: 40.42, tier: 'Tier 9' }, // Moved down
    { id: 63, name: 'Tony Pollard', position: 'RB', team: 'TEN', adp: 63.36, tier: 'Tier 10' },
    { id: 64, name: 'Isiah Pacheco', position: 'RB', team: 'KC', adp: 64.33, tier: 'Tier 10' },
    { id: 65, name: 'Patrick Mahomes II', position: 'QB', team: 'KC', adp: 64.73, tier: 'Tier 10' },
    { id: 66, name: 'Jaylen Waddle', position: 'WR', team: 'MIA', adp: 66.58, tier: 'Tier 10' },
    { id: 67, name: 'RJ Harvey', position: 'RB', team: 'DEN', adp: 66.68, tier: 'Tier 10' },
    { id: 68, name: 'Aaron Jones Sr.', position: 'RB', team: 'MIN', adp: 69.08, tier: 'Tier 10' },
    { id: 69, name: 'Javonte Williams', position: 'RB', team: 'DAL', adp: 106.34, tier: 'Tier 10' }, // Moved up
    { id: 70, name: 'Jameson Williams', position: 'WR', team: 'DET', adp: 48.22, tier: 'Tier 10' }, // Tier moved down
    { id: 71, name: 'Rashee Rice', position: 'WR', team: 'KC', adp: 70.91, tier: 'Tier 11' },
    { id: 72, name: 'Baker Mayfield', position: 'QB', team: 'TB', adp: 71.35, tier: 'Tier 11' },
    { id: 73, name: 'Kaleb Johnson', position: 'RB', team: 'PIT', adp: 72.33, tier: 'Tier 11' },
    { id: 74, name: 'Brian Robinson Jr.', position: 'RB', team: 'WAS', adp: 72.51, tier: 'Tier 11' },
    { id: 75, name: 'Travis Hunter', position: 'WR', team: 'JAX', adp: 74.74, tier: 'Tier 11' },
    { id: 76, name: 'Bo Nix', position: 'QB', team: 'DEN', adp: 76.14, tier: 'Tier 11' },
    { id: 77, name: 'Tyrone Tracy Jr.', position: 'RB', team: 'NYG', adp: 79.3, tier: 'Tier 12' },
    { id: 78, name: 'Kyler Murray', position: 'QB', team: 'ARI', adp: 80.66, tier: 'Tier 12' },
    { id: 79, name: 'Joe Mixon', position: 'RB', team: 'HOU', adp: 81.4, tier: 'Tier 12' },
    { id: 80, name: 'Rome Odunze', position: 'WR', team: 'CHI', adp: 81.98, tier: 'Tier 12' },
    { id: 81, name: 'Chris Olave', position: 'WR', team: 'NO', adp: 83.11, tier: 'Tier 12' },
    { id: 82, name: 'Jerry Jeudy', position: 'WR', team: 'CLE', adp: 84.97, tier: 'Tier 12' },
    { id: 83, name: 'Ricky Pearsall', position: 'WR', team: 'SF', adp: 85.91, tier: 'Tier 12' },
    { id: 84, name: 'Jordan Addison', position: 'WR', team: 'MIN', adp: 87.24, tier: 'Tier 12' },
    { id: 85, name: 'Dak Prescott', position: 'QB', team: 'DAL', adp: 87.63, tier: 'Tier 12' },
    { id: 86, name: 'Jordan Mason', position: 'RB', team: 'SF', adp: 89.72, tier: 'Tier 13' },
    { id: 87, name: 'Deebo Samuel Sr.', position: 'WR', team: 'SF', adp: 91.77, tier: 'Tier 13' },
    { id: 88, name: 'Brock Purdy', position: 'QB', team: 'SF', adp: 92.18, tier: 'Tier 13' },
    { id: 89, name: 'Tucker Kraft', position: 'TE', team: 'GB', adp: 92.98, tier: 'Tier 13' },
    { id: 90, name: 'Jaylen Warren', position: 'RB', team: 'PIT', adp: 93.46, tier: 'Tier 13' },
    { id: 91, name: 'Jayden Reed', position: 'WR', team: 'GB', adp: 94.07, tier: 'Tier 13' },
    { id: 92, name: 'Jauan Jennings', position: 'WR', team: 'SF', adp: 94.78, tier: 'Tier 13' },
    { id: 93, name: 'Justin Fields', position: 'QB', team: 'PIT', adp: 94.92, tier: 'Tier 13' },
    { id: 94, name: 'David Njoku', position: 'TE', team: 'CLE', adp: 94.96, tier: 'Tier 13' },
    { id: 95, name: 'Travis Etienne Jr.', position: 'RB', team: 'JAX', adp: 95.79, tier: 'Tier 13' },
    { id: 96, name: 'Justin Herbert', position: 'QB', team: 'LAC', adp: 98.27, tier: 'Tier 13' },
    { id: 97, name: 'Jakobi Meyers', position: 'WR', team: 'LV', adp: 99.54, tier: 'Tier 14' },
    { id: 98, name: 'Jared Goff', position: 'QB', team: 'DET', adp: 102.24, tier: 'Tier 14' },
    { id: 99, name: 'Caleb Williams', position: 'QB', team: 'CHI', adp: 102.27, tier: 'Tier 14' },
    { id: 100, name: 'Stefon Diggs', position: 'WR', team: 'HOU', adp: 102.87, tier: 'Tier 14' },
    { id: 101, name: 'Tank Bigsby', position: 'RB', team: 'JAX', adp: 103, tier: 'Tier 14' },
    { id: 102, name: 'Rhamondre Stevenson', position: 'RB', team: 'NE', adp: 103.88, tier: 'Tier 14' },
    { id: 103, name: 'Drake Maye', position: 'QB', team: 'NE', adp: 104.55, tier: 'Tier 14' },
    { id: 104, name: 'J.K. Dobbins', position: 'RB', team: 'DEN', adp: 105.11, tier: 'Tier 14' },
    { id: 105, name: 'Zach Charbonnet', position: 'RB', team: 'SEA', adp: 105.61, tier: 'Tier 14' },
    { id: 106, name: 'Emeka Egbuka', position: 'WR', team: 'TB', adp: 105.7, tier: 'Tier 14' },
    { id: 107, name: 'Tyler Warren', position: 'TE', team: 'IND', adp: 105.92, tier: 'Tier 14' },
    { id: 108, name: 'Evan Engram', position: 'TE', team: 'DEN', adp: 106.25, tier: 'Tier 14' },
    { id: 109, name: 'Chris Godwin', position: 'WR', team: 'TB', adp: 108.35, tier: 'Tier 14' },
    { id: 110, name: 'Jordan Love', position: 'QB', team: 'GB', adp: 110.21, tier: 'Tier 15' },
    { id: 111, name: 'Khalil Shakir', position: 'WR', team: 'BUF', adp: 111.12, tier: 'Tier 15' },
    { id: 112, name: 'Najee Harris', position: 'RB', team: 'PIT', adp: 116.35, tier: 'Tier 15' },
    { id: 113, name: 'Trevor Lawrence', position: 'QB', team: 'JAX', adp: 116.76, tier: 'Tier 15' },
    { id: 114, name: 'Josh Downs', position: 'WR', team: 'IND', adp: 117.11, tier: 'Tier 15' },
    { id: 115, name: 'Matthew Golden', position: 'WR', team: 'GB', adp: 104.42, tier: 'Tier 14' },
    { id: 116, name: 'Cam Skattebo', position: 'RB', team: 'N/A', adp: 118.47, tier: 'Tier 15' },
    { id: 117, name: 'C.J. Stroud', position: 'QB', team: 'HOU', adp: 118.98, tier: 'Tier 15' },
    { id: 118, name: 'Dalton Kincaid', position: 'TE', team: 'BUF', adp: 119.62, tier: 'Tier 15' },
    { id: 119, name: 'Quinshon Judkins', position: 'RB', team: 'PHI', adp: 119.77, tier: 'Tier 15' },
    { id: 120, name: 'Dallas Goedert', position: 'TE', team: 'PHI', adp: 121.68, tier: 'Tier 6' },
    { id: 121, name: 'Cooper Kupp', position: 'WR', team: 'SEA', adp: 122.16, tier: 'Tier 15' },
    { id: 122, name: 'Darnell Mooney', position: 'WR', team: 'ATL', adp: 123.98, tier: 'Tier 16' },
    { id: 123, name: 'Michael Pittman Jr.', position: 'WR', team: 'IND', adp: 124.43, tier: 'Tier 16' },
    { id: 124, name: 'Keon Coleman', position: 'WR', team: 'BUF', adp: 125.25, tier: 'Tier 16' },
    { id: 125, name: 'Ray Davis', position: 'RB', team: 'BUF', adp: 126.99, tier: 'Tier 16' },
    { id: 126, name: 'Tyjae Spears', position: 'RB', team: 'TEN', adp: 127.51, tier: 'Tier 16' },
    { id: 127, name: 'Kyle Pitts Sr.', position: 'TE', team: 'ATL', adp: 127.97, tier: 'Tier 16' },
    { id: 128, name: 'J.J. McCarthy', position: 'QB', team: 'MIN', adp: 128.04, tier: 'Tier 16' },
    { id: 129, name: 'Brandon Aiyuk', position: 'WR', team: 'SF', adp: 129.92, tier: 'Tier 16' },
    { id: 130, name: 'Trey Benson', position: 'RB', team: 'ARI', adp: 132.3, tier: 'Tier 17' },
    { id: 131, name: 'Rashid Shaheed', position: 'WR', team: 'NO', adp: 132.37, tier: 'Tier 17' },
    { id: 132, name: 'Colston Loveland', position: 'TE', team: 'CHI', adp: 133.92, tier: 'Tier 17' },
    { id: 133, name: 'Tyler Allgeier', position: 'RB', team: 'ATL', adp: 137.23, tier: 'Tier 17' },
    { id: 134, name: 'Tua Tagovailoa', position: 'QB', team: 'MIA', adp: 138.33, tier: 'Tier 18' },
    { id: 135, name: 'Jake Ferguson', position: 'TE', team: 'DAL', adp: 139.25, tier: 'Tier 18' },
    { id: 136, name: 'Braelon Allen', position: 'RB', team: 'NYJ', adp: 139.3, tier: 'Tier 18' },
    { id: 137, name: 'Rashod Bateman', position: 'WR', team: 'BAL', adp: 140.98, tier: 'Tier 18' },
    { id: 138, name: 'Isaac Guerendo', position: 'RB', team: 'SF', adp: 141.41, tier: 'Tier 18' },
    { id: 139, name: 'Jaydon Blue', position: 'RB', team: 'DAL', adp: 143.44, tier: 'Tier 18' },
    { id: 140, name: 'Bryce Young', position: 'QB', team: 'CAR', adp: 145.35, tier: 'Tier 19' },
    { id: 141, name: 'Christian Kirk', position: 'WR', team: 'JAX', adp: 145.55, tier: 'Tier 19' },
    { id: 142, name: 'Nick Chubb', position: 'RB', team: 'CLE', adp: 145.68, tier: 'Tier 19' },
    { id: 143, name: 'Austin Ekeler', position: 'RB', team: 'WAS', adp: 145.93, tier: 'Tier 19' },
    { id: 144, name: 'Jerome Ford', position: 'RB', team: 'CLE', adp: 148.78, tier: 'Tier 19' },
    { id: 145, name: 'Marvin Mims Jr.', position: 'WR', team: 'DEN', adp: 150.12, tier: 'Tier 19' },
    { id: 146, name: 'Michael Penix Jr.', position: 'QB', team: 'ATL', adp: 151.43, tier: 'Tier 19' },
    { id: 147, name: 'Rico Dowdle', position: 'RB', team: 'DAL', adp: 151.71, tier: 'Tier 19' },
    { id: 148, name: 'Luther Burden III', position: 'WR', team: 'CHI', adp: 151.91, tier: 'Tier 19' },
    { id: 149, name: 'Hunter Henry', position: 'TE', team: 'NE', adp: 151.99, tier: 'Tier 19' },
    { id: 150, name: 'Jonnu Smith', position: 'TE', team: 'MIA', adp: 154.16, tier: 'Tier 19' },
    { id: 151, name: 'Jaylen Wright', position: 'RB', team: 'MIA', adp: 156.5, tier: 'Tier 20' },
    { id: 152, name: 'Cedric Tillman', position: 'WR', team: 'CLE', adp: 157.62, tier: 'Tier 20' },
    { id: 153, name: 'Matthew Stafford', position: 'QB', team: 'LAR', adp: 161.93, tier: 'Tier 20' },
    { id: 154, name: 'Isaiah Likely', position: 'TE', team: 'BAL', adp: 163.24, tier: 'Tier 20' },
    { id: 155, name: 'Bhayshul Tuten', position: 'RB', team: 'N/A', adp: 155.38, tier: 'Tier 19' },
    { id: 156, name: 'Romeo Doubs', position: 'WR', team: 'GB', adp: 164.12, tier: 'Tier 20' },
    { id: 157, name: 'Denver Broncos', position: 'DST', team: 'DEN', adp: 152.2, tier: 'Tier 19' },
    { id: 158, name: 'Jayden Higgins', position: 'WR', team: 'HOU', adp: 153.25, tier: 'Tier 19' },
    { id: 159, name: 'Dylan Sampson', position: 'RB', team: 'CLE', adp: 157.88, tier: 'Tier 20' },
    { id: 160, name: 'Zach Ertz', position: 'TE', team: 'WAS', adp: 168.34, tier: 'Tier 21' },
    { id: 161, name: 'Marquise Brown', position: 'WR', team: 'KC', adp: 169.16, tier: 'Tier 21' },
    { id: 162, name: 'Geno Smith', position: 'QB', team: 'SEA', adp: 170.82, tier: 'Tier 21' },
    { id: 163, name: 'Jalen McMillan', position: 'WR', team: 'TB', adp: 170.62, tier: 'Tier 21' },
    { id: 164, name: 'Roschon Johnson', position: 'RB', team: 'CHI', adp: 173.51, tier: 'Tier 21' },
    { id: 165, name: 'Tre\' Harris', position: 'WR', team: 'LAC', adp: 171.8, tier: 'Tier 21' },
    { id: 166, name: 'Quentin Johnston', position: 'WR', team: 'LAC', adp: 174.9, tier: 'Tier 21' },
    { id: 167, name: 'Kyle Williams', position: 'WR', team: 'NE', adp: 177.23, tier: 'Tier 21' },
    { id: 168, name: 'Philadelphia Eagles', position: 'DST', team: 'PHI', adp: 162.99, tier: 'Tier 20' },
    { id: 169, name: 'Joshua Palmer', position: 'WR', team: 'LAC', adp: 177.92, tier: 'Tier 21' },
    { id: 170, name: 'Blake Corum', position: 'RB', team: 'LAR', adp: 181.59, tier: 'Tier 22' },
    { id: 171, name: 'Baltimore Ravens', position: 'DST', team: 'BAL', adp: 170.41, tier: 'Tier 21' },
    { id: 172, name: 'Pittsburgh Steelers', position: 'DST', team: 'PIT', adp: 167.95, tier: 'Tier 21' },
    { id: 173, name: 'Adam Thielen', position: 'WR', team: 'CAR', adp: 185.17, tier: 'Tier 22' },
    { id: 174, name: 'Keenan Allen', position: 'WR', team: 'CHI', adp: 173.76, tier: 'Tier 21' },
    { id: 175, name: 'Minnesota Vikings', position: 'DST', team: 'MIN', adp: 174.41, tier: 'Tier 21' },
    { id: 176, name: 'MarShawn Lloyd', position: 'RB', team: 'GB', adp: 187.93, tier: 'Tier 22' },
    { id: 177, name: 'DeAndre Hopkins', position: 'WR', team: 'BAL', adp: 191.58, tier: 'Tier 23' },
    { id: 178, name: 'Demario Douglas', position: 'WR', team: 'NE', adp: 192.15, tier: 'Tier 23' },
    { id: 179, name: 'Sam Darnold', position: 'QB', team: 'MIN', adp: 192.48, tier: 'Tier 23' },
    { id: 180, name: 'Xavier Legette', position: 'WR', team: 'CAR', adp: 190.43, tier: 'Tier 23'
